// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BS_1step_cpp
Rcpp::List BS_1step_cpp(const Eigen::MatrixXd& mt, const Eigen::MatrixXd& Mt, const Eigen::MatrixXd& st1, const Eigen::MatrixXd& St1, const Eigen::MatrixXd& at1, const Eigen::MatrixXd& At1, const Eigen::MatrixXd& Gt1, double delta);
RcppExport SEXP _spDBL_BS_1step_cpp(SEXP mtSEXP, SEXP MtSEXP, SEXP st1SEXP, SEXP St1SEXP, SEXP at1SEXP, SEXP At1SEXP, SEXP Gt1SEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type mt(mtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Mt(MtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type st1(st1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type St1(St1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type at1(at1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type At1(At1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Gt1(Gt1SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(BS_1step_cpp(mt, Mt, st1, St1, at1, At1, Gt1, delta));
    return rcpp_result_gen;
END_RCPP
}
// FF_1step_cpp
Rcpp::List FF_1step_cpp(const Eigen::MatrixXd& Yt, const Eigen::MatrixXd& Ft, const Eigen::MatrixXd& Gt, const Eigen::MatrixXd& Wt, const Eigen::MatrixXd& Vt, const Eigen::MatrixXd& mt_1, const Eigen::MatrixXd& Mt_1, double nt_1, const Eigen::MatrixXd& Dt_1, double delta);
RcppExport SEXP _spDBL_FF_1step_cpp(SEXP YtSEXP, SEXP FtSEXP, SEXP GtSEXP, SEXP WtSEXP, SEXP VtSEXP, SEXP mt_1SEXP, SEXP Mt_1SEXP, SEXP nt_1SEXP, SEXP Dt_1SEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Yt(YtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Ft(FtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Gt(GtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Wt(WtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Vt(VtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type mt_1(mt_1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Mt_1(Mt_1SEXP);
    Rcpp::traits::input_parameter< double >::type nt_1(nt_1SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Dt_1(Dt_1SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(FF_1step_cpp(Yt, Ft, Gt, Wt, Vt, mt_1, Mt_1, nt_1, Dt_1, delta));
    return rcpp_result_gen;
END_RCPP
}
// rmn_cpp
Eigen::MatrixXd rmn_cpp(const Eigen::MatrixXd& m, const Eigen::MatrixXd& U, const Eigen::MatrixXd& V);
RcppExport SEXP _spDBL_rmn_cpp(SEXP mSEXP, SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type U(USEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(rmn_cpp(m, U, V));
    return rcpp_result_gen;
END_RCPP
}
// rmn_chol_cpp
Eigen::MatrixXd rmn_chol_cpp(const Eigen::MatrixXd& m, const Eigen::MatrixXd& RM, const Eigen::MatrixXd& RSigma);
RcppExport SEXP _spDBL_rmn_chol_cpp(SEXP mSEXP, SEXP RMSEXP, SEXP RSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type RM(RMSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type RSigma(RSigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmn_chol_cpp(m, RM, RSigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spDBL_BS_1step_cpp", (DL_FUNC) &_spDBL_BS_1step_cpp, 8},
    {"_spDBL_FF_1step_cpp", (DL_FUNC) &_spDBL_FF_1step_cpp, 10},
    {"_spDBL_rmn_cpp", (DL_FUNC) &_spDBL_rmn_cpp, 3},
    {"_spDBL_rmn_chol_cpp", (DL_FUNC) &_spDBL_rmn_chol_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_spDBL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
