# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BS_1step_cpp <- function(mt, Mt, st1, St1, at1, At1, Gt1, delta = 1.0) {
    .Call(`_spDBL_BS_1step_cpp`, mt, Mt, st1, St1, at1, At1, Gt1, delta)
}

FF_1step_cpp <- function(Yt, Ft, Gt, Wt, Vt, mt_1, Mt_1, nt_1, Dt_1, delta = 1.0) {
    .Call(`_spDBL_FF_1step_cpp`, Yt, Ft, Gt, Wt, Vt, mt_1, Mt_1, nt_1, Dt_1, delta)
}

rmn_cpp <- function(m, U, V) {
    .Call(`_spDBL_rmn_cpp`, m, U, V)
}

rmn_chol_cpp <- function(m, RM, RSigma) {
    .Call(`_spDBL_rmn_chol_cpp`, m, RM, RSigma)
}

